{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "microservice-chart.fullname" . }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
spec:
  groups:
    - name: {{ .Values.serviceName }}.rules
      rules:
        {{- tpl (toYaml .Values.prometheusRule.rules) . | nindent 8 }}
{{- end }}
