apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice-chart.fullname" . }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.serviceName }}
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
      name: http
