apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: selfcare-platform
  namespace: argocd
spec:
  description: Selfcare microservices and operator overlays
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
